project:
  type: website

website:
  title: "Tanner Delpier"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tdelpier
      - icon: twitter
        href: https://twitter.com/tdelpier
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

